name: CI

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          # AGP 8.1.*
          - gradle: 8.4
            agp: 8.1.4
          - gradle: 8.3
            agp: 8.1.4
          - gradle: 8.2.1
            agp: 8.1.4
          - gradle: 8.1.1
            agp: 8.1.4
          - gradle: 8.0.2
            agp: 8.1.4

          # AGP 8.0.*
          - gradle: 8.4
            agp: 8.0.2
          - gradle: 8.3
            agp: 8.0.2
          - gradle: 8.2.1
            agp: 8.0.2
          - gradle: 8.1.1
            agp: 8.0.2
          - gradle: 8.0.2
            agp: 8.0.2

          # AGP 7.4.*
          - gradle: 8.4
            agp: 7.4.2
          - gradle: 8.3
            agp: 7.4.2
          - gradle: 8.2.1
            agp: 7.4.2
          - gradle: 8.1.1
            agp: 7.4.2
          - gradle: 8.0.2
            agp: 7.4.2
          - gradle: 7.6.3
            agp: 7.4.2
          - gradle: 7.5.1
            agp: 7.4.2

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Publish plugin to local Maven repo
        run: ./gradlew :prefiller:publishToMavenLocal -PexcludeSample --stacktrace

      - name: Run tests
        env:
          GRADLE_VERSION: ${{ matrix.gradle }}
          AGP_VERSION: ${{ matrix.agp }}
          TEST_JDK_VERSION: ${{ matrix.jdk || '17' }}
        run: ./gradlew test --stacktrace
