name: Publish to S3 maven repository

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Publish plugin
        env:
          YANDEX_S3_ACCESS_KEY_ID: ${{ secrets.YANDEX_S3_ACCESS_KEY_ID }}
          YANDEX_S3_SECRET_ACCESS_KEY: ${{ secrets.YANDEX_S3_SECRET_ACCESS_KEY }}
        run: >
          ./gradlew 
          -I gradle/ci.publish.gradle.kts
          -Dorg.gradle.s3.endpoint=https://storage.yandexcloud.net
          -PexcludeSample
          prefiller:publishAllPublicationsToPixnewsS3Repository
          --stacktrace

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        if: ${{ failure() }}
        with:
          name: build-outputs
          path: '**/build/outputs'
